/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function MpRobot2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/mp_robotv2.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.idleNew.play()
  })
  return (
    <group ref={group} castShadow {...props} dispose={null}>
      <group name="metarig" position={[1.08, -0.22, -0.1]} rotation={[0, 0, 0]} scale={1}>
        <primitive object={nodes.spine} />
        <group name="slate">
          <skinnedMesh
            castShadow
            frustumCulled={false}
            geometry={nodes.Cube002.geometry}
            material={materials['Material.002']}
            skeleton={nodes.Cube002.skeleton}
          />
          <skinnedMesh
            castShadow
            frustumCulled={false}
            geometry={nodes.Cube002_1.geometry}
            material={materials['Material.003']}
            skeleton={nodes.Cube002_1.skeleton}
          />
          <skinnedMesh 
            castShadow
            frustumCulled={false}
            geometry={nodes.Cube002_2.geometry}
            material={materials['Material.005']}
            skeleton={nodes.Cube002_2.skeleton}
          />
          <skinnedMesh
            castShadow
            frustumCulled={false}
            geometry={nodes.Cube002_3.geometry}
            material={materials['Material.007']}
            skeleton={nodes.Cube002_3.skeleton}
          />
          <skinnedMesh
            castShadow
            frustumCulled={false}
            geometry={nodes.Cube002_4.geometry}
            material={materials['Material.008']}
            skeleton={nodes.Cube002_4.skeleton}
          />
          <skinnedMesh
            castShadow
            frustumCulled={false}
            geometry={nodes.Cube002_5.geometry}
            material={materials['Material.009']}
            skeleton={nodes.Cube002_5.skeleton}
          />
        </group>
        <skinnedMesh
          castShadow
          frustumCulled={false}
          name="bowtie"
          geometry={nodes.bowtie.geometry}
          material={materials['Material.011']}
          skeleton={nodes.bowtie.skeleton}
        />
        <skinnedMesh
          castShadow
          frustumCulled={false}
          name="Cane"
          geometry={nodes.Cane.geometry}
          material={materials.caneMat}
          skeleton={nodes.Cane.skeleton}
        />
        <skinnedMesh
          frustumCulled={false} 
          castShadow
          name="hat"
          geometry={nodes.hat.geometry}
          material={materials.blackHat}
          skeleton={nodes.hat.skeleton}
        />
        <skinnedMesh
          frustumCulled={false}
          castShadow
          name="000_Sphere003_Mustache_0"
          geometry={nodes['000_Sphere003_Mustache_0'].geometry}
          material={materials['Mustache_65b81f73-7620-48d5-97f5-9b752d8e6f7d']}
          skeleton={nodes['000_Sphere003_Mustache_0'].skeleton}
        />
        <skinnedMesh
          castShadow
          frustumCulled={false}
          geometry={nodes.cleanup.geometry}
          material={materials['Material.001']}
          skeleton={nodes.cleanup.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/mp_robotv2.glb')
