/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function StudiBuddiRobot(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/studibuddi.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.idle.play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1.08, -0.22, -0.1]} rotation={[0, 0, 0]} scale={1}>
        <primitive object={nodes.spine} />
        <group name="slate">
          <skinnedMesh
            geometry={nodes.Cube002.geometry}
            material={materials['Material.002']}
            skeleton={nodes.Cube002.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            geometry={nodes.Cube002_1.geometry}
            material={materials['Material.003']}
            skeleton={nodes.Cube002_1.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            geometry={nodes.Cube002_2.geometry}
            material={materials['Material.007']}
            skeleton={nodes.Cube002_2.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            geometry={nodes.Cube002_3.geometry}
            material={materials['Material.008']}
            skeleton={nodes.Cube002_3.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            geometry={nodes.Cube002_4.geometry}
            material={materials['Material.010']}
            skeleton={nodes.Cube002_4.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            geometry={nodes.Cube002_5.geometry}
            material={materials['Material.009']}
            skeleton={nodes.Cube002_5.skeleton}
            frustumCulled={false}
          />
        </group>
        <skinnedMesh
          geometry={nodes.Cube001.geometry}
          material={materials['Material.001']}
          skeleton={nodes.Cube001.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Cube001_1.geometry}
          material={materials['Material.011']}
          skeleton={nodes.Cube001_1.skeleton}
          frustumCulled={false}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/studibuddi.glb')
