/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function ZombieRobot7(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/zombie_robot_v70.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.idleNew.play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1.08, -0.22, -0.1]} rotation={[0, 0, 0]} scale={1}>
        <primitive object={nodes.spine} />
        <group name="slate">
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.Cube002.geometry}
            material={materials['Material.002']}
            skeleton={nodes.Cube002.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.Cube002_1.geometry}
            material={materials['Material.003']}
            skeleton={nodes.Cube002_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.Cube002_2.geometry}
            material={materials['Material.005']}
            skeleton={nodes.Cube002_2.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.Cube002_3.geometry}
            material={materials['Material.006']}
            skeleton={nodes.Cube002_3.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}

            geometry={nodes.Cube002_4.geometry}
            material={materials['Material.007']}
            skeleton={nodes.Cube002_4.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.Cube002_5.geometry}
            material={materials['Material.008']}
            skeleton={nodes.Cube002_5.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.Cube002_6.geometry}
            material={materials['Material.004']}
            skeleton={nodes.Cube002_6.skeleton}
          />
        </group>
        <group name="wires">
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.NurbsPath002.geometry}
            material={materials['green wire']}
            skeleton={nodes.NurbsPath002.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.NurbsPath002_1.geometry}
            material={materials.bluewire}
            skeleton={nodes.NurbsPath002_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.NurbsPath002_2.geometry}
            material={materials.redwire}
            skeleton={nodes.NurbsPath002_2.skeleton}
          />
        </group>
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Cube001.geometry}
          material={materials.image_only}
          skeleton={nodes.Cube001.skeleton}
        />
        <skinnedMesh
          frustumCulled={false}
          geometry={nodes.Cube001_1.geometry}
          material={materials.mouth}
          skeleton={nodes.Cube001_1.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/zombie_robot_v70.glb')
